// cityForecast
export const SET_LOCATION_OPTIONS = 'SET_LOCATION_OPTIONS';
export const SET_LOCATION = 'SET_LOCATION';
export const FETCH_LOCATION_FORECAST = 'FETCH_LOCATION_FORECAST';
export const TOGGLE_TEMPERATURE_TYPE = 'TOGGLE_TEMPERATURE_TYPE';

// favorites
export const TOGGLE_FAV_LOCATION = 'TOGGLE_FAV_LOCATION';
export const UPDATE_FAVOURITES_WEATHER = 'UPDATE_FAVOURITES_WEATHER';

// appMode
export const TOGGLE_APP_MODE = 'TOGGLE_APP_MODE';
